### ISSUE TITLE
java.lang.IllegalStateException when diffing APK

### ISSUE THREAD

**Issue by shauvik** [JakeWharton/diffuse#72]
Getting this exception when working with an APK.
```
Exception in thread "main" java.lang.IllegalStateException: Check failed.
	at com.jakewharton.diffuse.Manifest$Companion.toDocument(Manifest.kt:81)
	at com.jakewharton.diffuse.Manifest$Companion.toManifest$diffuse(Manifest.kt:48)
	at com.jakewharton.diffuse.Apk$Companion.parse(Apk.kt:31)
	at com.jakewharton.diffuse.DiffCommand$inputOptions$2.parse(diffuse.kt:76)
	at com.jakewharton.diffuse.DiffCommand.run(diffuse.kt:135)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:139)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:215)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:212)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:230)
	at com.jakewharton.diffuse.Diffuse.main(diffuse.kt:41)
```
If i disable the check in `com.jakewharton.diffuse.Manifest` then it proceeds and completes execution. 
```
check(namespacesInScope.put(chunk.uri, "${chunk.prefix}:") == null)
```

Looking at the APK extracted with apktool, it seems like we have several resource XMLs with the URIs in question. So, perhaps those are causing this issue...

**Comment by JakeWharton** [comment]
This seems like it would happen if you defined the same namespace URL to two XML namespace prefixes. I believe this code is heavily derived from Android Studio so it's likely a problem there as well.

I'll take a look when I get a chance.
