### ISSUE TITLE
Exception in thread "main" java.util.zip.ZipException: invalid entry compressed size (expected 1276 but got 1272 bytes)

### ISSUE THREAD

**Issue by THEONE10211024** [JakeWharton/diffuse#77]
Exception in thread "main" java.util.zip.ZipException: invalid entry compressed size (expected 1276 but got 1272 bytes)
	at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:389)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
	at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:140)
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:118)
	at com.jakewharton.diffuse.ExtensionsKt$entries$1$iterator$1.hasNext(extensions.kt:73)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:176)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:722)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:752)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:743)
	at com.jakewharton.diffuse.io.ZipKt.mapEntries(Zip.kt:70)
	at com.jakewharton.diffuse.io.ZipKt.toZip(Zip.kt:96)
	at com.jakewharton.diffuse.io.PathInput.toZip(Input.kt:43)
	at com.jakewharton.diffuse.Apk$Companion.parse(Apk.kt:28)
	at com.jakewharton.diffuse.DiffCommand$inputOptions$2.parse(diffuse.kt:76)
	at com.jakewharton.diffuse.DiffCommand.run(diffuse.kt:135)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:139)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:215)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:212)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:230)
	at com.jakewharton.diffuse.Diffuse.main(diffuse.kt:41)

**Comment by THEONE10211024** [comment]
command: /Users/xiayong/Downloads/diffuse-master/diffuse/build/diffuse diff  /Users/xiayong/Downloads/bad1.apk  /Users/xiayong/Downloads/good.apk

**Comment by JakeWharton** [comment]
Are you able to share the broken APK? How can I reproduce/test this in order to establish a fix?

**Comment by THEONE10211024** [comment]
I send the APK to your email -> j@ke.fyi

**Comment by JakeWharton** [comment]
Thanks! I will take a look this week.

**Comment by JakeWharton** [comment]
Also what's the output of `java -version`?

**Comment by THEONE10211024** [comment]
![image](https://user-images.githubusercontent.com/11347899/91929735-a5328580-ed11-11ea-93b8-6f1fcfebca0a.png)

**Comment by fabioportieri** [comment]
seems like a bug in the jdk

https://bugs.openjdk.org/browse/JDK-8044727

tho it's marked as resolved i had the same issue, and switching it to use jdk11 didn't solve it either

**Comment by JakeWharton** [comment]
Without a reproducer I can't look into this. Ultimately it's probably a JDK problem that we have no control over, as referenced, but still worth debugging.

I tried to download the link sent to my email 3+ years ago but it had expired and never received a reply on resend request.
